[workspace]
resolver = "3"
members = [
    "crates/openrustygb-domain",
    "crates/openrustygb-driver-api",
    "crates/openrustygb-runtime",
    "crates/openrustygb-transport-hid",
    "crates/drivers/hyperx-pulsefire-haste2",
    "crates/drivers/gamesir-nova-lite-2",
    "crates/drivers/faustus-keyboard",
    "crates/drivers/lexip-np93-alpha",
    "crates/drivers/n5312a-mouse",
    "crates/drivers/patriot-viper-v550",
    "crates/drivers/dream-cheeky-webmail-notifier",
    "crates/drivers/nvidia-esa-xps-730x",
    "crates/drivers/madcatz-cyborg-light",
    "crates/drivers/thingm-blink1-mk2",
    "crates/drivers/msi-3-zone-keyboard",
    "crates/drivers/nzxt-lift-mouse",
    "crates/drivers/asus-monitor",
    "crates/drivers/tecknet-m008",
    "crates/drivers/hyperx-mousemat",
    "crates/drivers/lego-dimensions-toypad",
    "crates/drivers/aoc-amm700-mousemat",
    "crates/drivers/aoc-gm500-mouse",
    "crates/drivers/gigabyte-aorus-m2",
    "crates/drivers/dark-project-kd3b-v2",
    "crates/drivers/elgato-stream-deck-mk2",
    "crates/drivers/areson-mice",
    "crates/drivers/sayodevice-e1",
    "crates/drivers/wushi-l50",
    "crates/drivers/redragon-mice",
    "crates/drivers/gigabyte-aorus-c300-glass",
    "crates/drivers/clevo-lightbar",
    "crates/drivers/skydimo-sk0902",
    "crates/drivers/ek-loop-connect",
    "crates/drivers/luxafor-flag",
    "crates/drivers/instant-mice",
    "crates/drivers/glorious-model-i",
    "crates/drivers/hyte-keeb-tkl",
    "crates/drivers/intel-arc-a770-le",
    "crates/drivers/skyloong-gk104-pro",
    "crates/drivers/anne-pro-2",
    "crates/drivers/ionico",
    "crates/drivers/xpg-summoner",
    "crates/drivers/ducky-keyboard",
    "crates/drivers/thermaltake-poseidon-z-rgb",
    "crates/openrustygb-app",
    "xtask",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.88"
license = "GPL-2.0-only"
repository = "https://github.com/NitroDiesel/OpenRustyGB"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_debug_implementations = "warn"
unused_must_use = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
