[workspace]
resolver = "3"
members = [
    "crates/openrustygb-domain",
    "crates/openrustygb-driver-api",
    "crates/openrustygb-runtime",
    "crates/openrustygb-transport-hid",
    "crates/drivers/hyperx-pulsefire-haste2",
    "crates/drivers/gamesir-nova-lite-2",
    "crates/drivers/faustus-keyboard",
    "crates/drivers/lexip-np93-alpha",
    "crates/drivers/n5312a-mouse",
    "crates/drivers/patriot-viper-v550",
    "crates/drivers/dream-cheeky-webmail-notifier",
    "crates/drivers/nvidia-esa-xps-730x",
    "crates/openrustygb-app",
    "xtask",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.88"
license = "GPL-2.0-only"
repository = "https://github.com/NitroDiesel/OpenRustyGB"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_debug_implementations = "warn"
unused_must_use = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
