[package]
name = "openrustygb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
openrustygb-driver-aoc-amm700-mousemat = { path = "../drivers/aoc-amm700-mousemat" }
openrustygb-driver-asus-monitor = { path = "../drivers/asus-monitor" }
openrustygb-domain = { path = "../openrustygb-domain" }
openrustygb-driver-api = { path = "../openrustygb-driver-api" }
openrustygb-driver-areson-mice = { path = "../drivers/areson-mice" }
openrustygb-driver-dream-cheeky-webmail-notifier = { path = "../drivers/dream-cheeky-webmail-notifier" }
openrustygb-driver-dark-project-kd3b-v2 = { path = "../drivers/dark-project-kd3b-v2" }
openrustygb-driver-elgato-stream-deck-mk2 = { path = "../drivers/elgato-stream-deck-mk2" }
openrustygb-driver-faustus-keyboard = { path = "../drivers/faustus-keyboard" }
openrustygb-driver-gamesir-nova-lite-2 = { path = "../drivers/gamesir-nova-lite-2" }
openrustygb-driver-gigabyte-aorus-m2 = { path = "../drivers/gigabyte-aorus-m2" }
openrustygb-driver-hyperx-pulsefire-haste2 = { path = "../drivers/hyperx-pulsefire-haste2" }
openrustygb-driver-hyperx-mousemat = { path = "../drivers/hyperx-mousemat" }
openrustygb-driver-lexip-np93-alpha = { path = "../drivers/lexip-np93-alpha" }
openrustygb-driver-lego-dimensions-toypad = { path = "../drivers/lego-dimensions-toypad" }
openrustygb-driver-madcatz-cyborg-light = { path = "../drivers/madcatz-cyborg-light" }
openrustygb-driver-msi-3-zone-keyboard = { path = "../drivers/msi-3-zone-keyboard" }
openrustygb-driver-n5312a-mouse = { path = "../drivers/n5312a-mouse" }
openrustygb-driver-nvidia-esa-xps-730x = { path = "../drivers/nvidia-esa-xps-730x" }
openrustygb-driver-nzxt-lift-mouse = { path = "../drivers/nzxt-lift-mouse" }
openrustygb-driver-patriot-viper-v550 = { path = "../drivers/patriot-viper-v550" }
openrustygb-driver-redragon-mice = { path = "../drivers/redragon-mice" }
openrustygb-driver-sayodevice-e1 = { path = "../drivers/sayodevice-e1" }
openrustygb-driver-thingm-blink1-mk2 = { path = "../drivers/thingm-blink1-mk2" }
openrustygb-driver-tecknet-m008 = { path = "../drivers/tecknet-m008" }
openrustygb-driver-wushi-l50 = { path = "../drivers/wushi-l50" }
openrustygb-runtime = { path = "../openrustygb-runtime" }
openrustygb-transport-hid = { path = "../openrustygb-transport-hid" }

[lints]
workspace = true
