[package]
name = "openrustygb-driver-lego-dimensions-toypad"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
openrustygb-domain = { path = "../../openrustygb-domain" }
openrustygb-driver-api = { path = "../../openrustygb-driver-api" }

[lints]
workspace = true
